// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task12NetCoreBackEnd.DataBase;

#nullable disable

namespace Task12NetCoreBackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220509113206_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.DayReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DayIncome")
                        .HasColumnType("int");

                    b.Property<int>("DayOutcome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DayReports");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.FinanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Income")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinanceTypes");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.MoneyOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayReportId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinanceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<int?>("MonthReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayReportId");

                    b.HasIndex("FinanceTypeId");

                    b.HasIndex("MonthReportId");

                    b.ToTable("MoneyOperations");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.MonthReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MonthIncome")
                        .HasColumnType("int");

                    b.Property<int>("MonthOutcome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonthReports");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.MoneyOperation", b =>
                {
                    b.HasOne("Task12NetCoreBackEnd.Models.DayReport", null)
                        .WithMany("DayOperations")
                        .HasForeignKey("DayReportId");

                    b.HasOne("Task12NetCoreBackEnd.Models.FinanceType", "FinanceType")
                        .WithMany("MoneyOperations")
                        .HasForeignKey("FinanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task12NetCoreBackEnd.Models.MonthReport", null)
                        .WithMany("MonthOperations")
                        .HasForeignKey("MonthReportId");

                    b.Navigation("FinanceType");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.DayReport", b =>
                {
                    b.Navigation("DayOperations");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.FinanceType", b =>
                {
                    b.Navigation("MoneyOperations");
                });

            modelBuilder.Entity("Task12NetCoreBackEnd.Models.MonthReport", b =>
                {
                    b.Navigation("MonthOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
